### ISSUE TITLE
UDID validation needed for iPhone XS - it is no longer 40 digits and has a dash in it

### ISSUE THREAD

**Issue by jhtin** [libimobiledevice/ideviceinstaller#100]
The udid validation assumes it is 40 characters and breaks when an iphone XS udid is used.

**Comment by nikias** [comment]
Oh interesting. I was about to make some changes to libusbmuxd so this is a good time to make it compatible.

**Comment by pradeep2832** [comment]
Yes we had to modify ideviceinstaller to remove the 40 char validation and that made it work .

No other issues seen in our testing with XS and XS max

**Comment by umutuzgur** [comment]
One example can be this one `00008020-0016311A0298002E`

**Comment by nikias** [comment]
@umutuzgur can you post a sample output of ideviceinfo of such a device? You can also email it to me for more privacy. my email is in the file header comment. thanks.

**Comment by munimkazia** [comment]
It basically doesn't recognise the command at all. 
For example: 

```
$ idevice_id -l
00008020000XXXXXXXXXXXXX
$ ideviceinfo -u 00008020000XXXXXXXXXXXXX
Usage: ideviceinfo [OPTIONS]
Show information about a connected device.

  -d, --debug       enable communication debugging
  -s, --simple      use a simple connection to avoid auto-pairing with the device
  -u, --udid UDID   target specific device by its 40-digit device UDID
  -q, --domain NAME set domain of query to NAME. Default: None
  -k, --key NAME    only query key specified by NAME. Default: All keys.
  -x, --xml     output information as xml plist instead of key/value pairs
  -h, --help        prints usage information

  Known domains are:

  com.apple.disk_usage
  com.apple.disk_usage.factory
  com.apple.mobile.battery
  com.apple.iqagent
  com.apple.purplebuddy
  com.apple.PurpleBuddy
  com.apple.mobile.chaperone
  com.apple.mobile.third_party_termination
  com.apple.mobile.lockdownd
  com.apple.mobile.lockdown_cache
  com.apple.xcode.developerdomain
  com.apple.international
  com.apple.mobile.data_sync
  com.apple.mobile.tethered_sync
  com.apple.mobile.mobile_application_usage
  com.apple.mobile.backup
  com.apple.mobile.nikita
  com.apple.mobile.restriction
  com.apple.mobile.user_preferences
  com.apple.mobile.sync_data_class
  com.apple.mobile.software_behavior
  com.apple.mobile.iTunes.SQLMusicLibraryPostProcessCommands
  com.apple.mobile.iTunes.accessories
  com.apple.mobile.internal
  com.apple.mobile.wireless_lockdown
  com.apple.fairplay
  com.apple.iTunes
  com.apple.mobile.iTunes.store
  com.apple.mobile.iTunes

Homepage: <http://libimobiledevice.org>
```

**Comment by pradeep2832** [comment]
@munimkazia - Try Idevicepair and then ideviceinfo and it works

**Comment by munimkazia** [comment]
@pradeep2832 Thanks, thats a nice trick.. idevicepair without a UDID specified does work, but the problem is I have multiple devices connected to my machine. As a workaround, I can selectively add/remove devices as required, but ultimately I need to work with multiple devices.

**Comment by pradeep2832** [comment]
@munimkazia - did you try idevicepair with udid and ideviceinfo with udid ? 

It worked for us in xs and XS max . We connect 5 devices at the same time to our app .

**Comment by pradeep2832** [comment]
Ya looks like the latest idevicepair is not working correct . when multiple devices are connected and if I trust device A , when I try to pair device B which is yet to be trusted ... it comes with a message saying it’s already paired with A udid

**Comment by nikias** [comment]
I removed the redundant length check completely.

**Comment by SealviewTW** [comment]
I am still facing the problem described by @munimkazia 

libimobiledevice HEAD-f37b592_2 is already installed and up-to-date

ideviceinfo -u 00008020000625E11A84002E
Usage: ideviceinfo [OPTIONS]
Show information about a connected device.

  -d, --debug		enable communication debugging
  -s, --simple		use a simple connection to avoid auto-pairing with the device
  -u, --udid UDID	target specific device by its 40-digit device UDID
  -q, --domain NAME	set domain of query to NAME. Default: None
  -k, --key NAME	only query key specified by NAME. Default: All keys.
  -x, --xml		output information as xml plist instead of key/value pairs
  -h, --help		prints usage information

  Known domains are:

  com.apple.disk_usage
  com.apple.disk_usage.factory
  com.apple.mobile.battery
  com.apple.iqagent
  com.apple.purplebuddy
  com.apple.PurpleBuddy
  com.apple.mobile.chaperone
  com.apple.mobile.third_party_termination
  com.apple.mobile.lockdownd
  com.apple.mobile.lockdown_cache
  com.apple.xcode.developerdomain
  com.apple.international
  com.apple.mobile.data_sync
  com.apple.mobile.tethered_sync
  com.apple.mobile.mobile_application_usage
  com.apple.mobile.backup
  com.apple.mobile.nikita
  com.apple.mobile.restriction
  com.apple.mobile.user_preferences
  com.apple.mobile.sync_data_class
  com.apple.mobile.software_behavior
  com.apple.mobile.iTunes.SQLMusicLibraryPostProcessCommands
  com.apple.mobile.iTunes.accessories
  com.apple.mobile.internal
  com.apple.mobile.wireless_lockdown
  com.apple.fairplay
  com.apple.iTunes
  com.apple.mobile.iTunes.store
  com.apple.mobile.iTunes

idevicepair -u 00008020-000625E11A84002E
idevicepair: invalid UDID specified (length != 40)

idevicepair - Manage host pairings with devices and usbmuxd.

Usage: idevicepair [OPTIONS] COMMAND

 Where COMMAND is one of:
  systembuid   print the system buid of the usbmuxd host
  hostid       print the host id for target device
  pair         pair device with this host
  validate     validate if device is paired with this host
  unpair       unpair device with this host
  list         list devices paired with this host

 The following OPTIONS are accepted:
  -d, --debug      enable communication debugging
  -u, --udid UDID  target specific device by its 40-digit device UDID
  -h, --help       prints usage information

Homepage: <http://libimobiledevice.org>

**Comment by nikias** [comment]
@SealviewTW as you mentioned yourself, your codebase it at commit f37b592 which is not the latest... That commit is from March 21, 2018 but the fix for the new style UDIDs was added in commit b34e343 on October 1, 2018. So you clearly don't have the latest code.

**Comment by SealviewTW** [comment]
> @SealviewTW as you mentioned yourself, your codebase it at commit f37b592788bffcb9a70d211aef8b1f84751114ca which is not the latest... That commit is from March 21, 2018 but the fix for the new style UDIDs was added in commit b34e3435c21d06b3e5a4e7b5246fb6ddb6641a9f on October 1, 2018. So you clearly don't have the latest code.

I used brew install libimobiledevice --HEAD

is there any way to get the latest code with brew?

**Comment by nikias** [comment]
brew install --HEAD should get the latest. Not sure why it wouldn't work in your case. I also don't use brew so I can't really tell ;)

**Comment by SealviewTW** [comment]
Found out the problem, the brew installation needs extra steps.

The solution that worked for me is: https://github.com/flutter/flutter/issues/22595

**Comment by Shchvova** [comment]
This was fixed by this commit f14def7cd9303a0fe622732fae9830ae702fdd7c

**Comment by dgutie10** [comment]
I'm seeing this issues with:
ideviceinstaller HEAD-b37ce23_4
Catalina 10.15.3

**Comment by lsp84ch83** [comment]
brew install --HEAD usbmuxd
`Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 9860981 Apply changes towards a project wide common "autogen.sh" file`


brew install --HEAD libimobiledevice
`Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 35cbcbc configure: Fix libplist cython availability check to point to correct pkg-config file`


carried out  
`ideviceinstaller -u 00008020-XXXXXXXXXXXXX -l`
Will still report an error

**Comment by munimkazia** [comment]
@lsp84ch83 in my experience, homebrew never has the updated stuff for libimobiledevice.. I always build libimobiledevice from github source manually.

**Comment by lsp84ch83** [comment]
> 以我的经验@ lsp84ch83，自制软件从来没有libimobiledevice的更新内容。.我总是手动从github源构建libimobiledevice。

Manually build libimobiledevice from github source, always report various errors

![image](https://user-images.githubusercontent.com/25055457/84491981-01b87280-acd8-11ea-8e2b-0e238073ad54.png)

![image](https://user-images.githubusercontent.com/25055457/84492064-257bb880-acd8-11ea-82fe-4f1c7e629d53.png)

**Comment by munimkazia** [comment]
@lsp84ch83 can you try installing all dependencies from github? libplist and libusbmuxd are also projects inside libimobiledevice. I guess there is no script which builds all of it properly.
