### ISSUE TITLE
ideviceinstaller does not work on iOS 8 Beta 5

### ISSUE THREAD

**Issue by airmaster-mh** [libimobiledevice/ideviceinstaller#11]
iPhone Info (iPhone5S, iOS 8 Beta5)

command : ideviceinstaller -d -l
output :
usbmuxd_connect : Reading connect result…
usbmuxd_connect : Connect success!
ValidatePair success
usbmuxd_connect : Reading connect result…
usbmuxd_connect : Connect success!
Could not start com.apple.mobile.installation_proxy!

**Comment by LS2002** [comment]
Philantrop's way resolved this issue on iOS 8.3
To enable openssl for libimobiledevice, an easy way is to set enable_openssl=yes at line 130 of configure.ac

  if test "x$use_openssl" != "xyes"; then
    enable_openssl=yes
    echo "*** Note: OpenSSL support explicitly disabled ***"
  else
    enable_openssl=yes
  fi

**Comment by programmin1** [comment]
@LS2002 Still getting Could not start com.apple.mobile.installation_proxy! after doing those modifications, and running ./autogen.sh, make, and sudo checkinstall again, with libimobiledevice 1.2.1 from git.

Apparently this causes other issues other than not seeing apps' document folders, unable to inspect Safari may be due to this configuration? https://github.com/google/ios-webkit-debug-proxy/issues/74

If so can OpenSSL be set to be the default please?

**Comment by andrewmichaelsmith** [comment]
I'm using what seems to be the latest version (on ubuntu 16.04):

```
Unpacking libimobiledevice6:amd64 (1.2.0+dfsg-2.1build1) ...
Unpacking ideviceinstaller (1.1.0-0ubuntu2) ...
```

But I get the following error (also, no debug output?):

```
➜  ~ ideviceinstaller -d -l
Could not start com.apple.mobile.installation_proxy!
```

Any pointers about what might be the issue here?
